mybatis:
    configuration:
        cacheEnabled: false
        mapUnderscoreToCamelCase: true

    mapper-locations: classpath:/mapping/*.xml
server:
    port: 9377

spring:
    jpa:
        properties:
          hibernate:
              jdbc:
                lob:
                    non_contextual_creation: true
              dialect: org.hibernate.dialect.MySQLDialect
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ${DATABASE_PASSWORD}
        url: ${DATABASE_URL}
        username: ${DATABASE_USERNAME}
    main:
        banner-mode: off
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        #    Knife4j配置
    mvc:
        path match:
            matching-strategy: ANT_PATH_MATCHER
    thymeleaf:
        cache: true
        check-template: true
        check-template-location: true
        servlet:
            content-type: text/html
        enabled: true
        encoding: UTF-8
        excluded-view-names: ''
        mode: HTML5
        prefix: classpath:/templates/
        suffix: .html
    application:
        name: Bodhi-files_system

    web:
        resources:
            static-locations: classpath:/static/
knife4j:
    enable: true
    openapi:
        title: Bodhi-files_system
        description: Bodhi后端微服务——文件系统
        version: 1.0.0
        concat:
            - jojo
        email: e1349686@u.nus.edu
        group:
          admin:
              group-name: 后端接口分组
              api-rule: package
              api-rule-resources:
                - com.nus.zkk.bodhifiles_system
